############################################################################################
# Exchange Adapter YAML config.
#
# - Sample config below currently set to run against Kraken.
# - All fields are mandatory unless stated otherwise.
# - BX-bot only supports running 1 exchange per bot.
# - The indentation levels are significant in YAML: https://en.wikipedia.org/wiki/YAML
#
# See the README "How do I write my own Exchange Adapter?" section for more details.
############################################################################################
---
exchange:

  # A friendly name for the Exchange. Value must be an alphanumeric string. Spaces are allowed.
  name: Kraken

  # For the adapter value, you must specify the fully qualified name of your Exchange Adapter class so the Trading Engine
  # can load and execute it. The class must be on the runtime classpath.
  adapter: com.gazbert.crypto.exchanges.KrakenExchangeAdapter

  authenticationConfig:
    # See https://www.kraken.com/u/settings/api to get your Kraken Trading API credentials.
    key: your-api-key
    secret: your-secret-key

  networkConfig:
    # This value is in SECONDS. It is the timeout value that the exchange adapter will wait on socket connect/socket read
    # when communicating