############################################################################################
# Exchange Adapter YAML config.
#
# DO NOT USE: See https://github.com/gazbert/crypto/pull/120
#
# - Sample config below currently set to run against GDAX (formerly Coinbase).
# - All fields are mandatory unless stated otherwise.
# - BX-bot only supports running 1 exchange per bot.
# - The indentation levels are significant in YAML: https://en.