############################################################################################
# Market YAML config.
#
# DO NOT USE: See https://github.com/gazbert/crypto/pull/120
#
# - All fields are mandatory unless stated otherwise.
# - Multiple market blocks can be listed.
# - The indentation levels are significant in YAML: https://en.wikipedia.org/wiki/YAML
############################################################################################
---
markets:

  # The id value is the market id as defined on the exchange, e.g. 'BTC-GBP'.
  - id: BTC-GBP

    # A friendly name for the market.
    # Value must be an alphanumeric string. Spaces are allowed. E.g. BTC/GBP
    name: BTC/GBP

    # The baseCurrency value is the currency short code for the base currency in the currency pair. When you buy or sell a
    # currency pair, you are performing that action on the base currency. The base currency is the commodity you are buying or
    # selling. E.g. in a BTC/GBP market, the first currency (BTC) is the base currency and the second currency (GBP) is the
    # counter currency.
    baseCurrency: BTC

    # The counterCurrency value is the currency short code for the counter currency in the